import type { Category, Diet, Ingredient, Recipe } from './domain/types'

const img = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=82`
const i = (id: string, name: string, amount: number, unit: string, category: Category, estimatedCost: number): Ingredient => ({ id, name, amount, unit, category, estimatedCost })
const r = (id: string, title: string, description: string, image: string, minutes: number, price: number, diet: Diet, tags: string[], nutrition: Recipe['nutrition'], ingredients: Ingredient[], steps: string[]): Recipe => ({ id, title, description, image, minutes, activeMinutes: Math.max(10, minutes - 8), servings: 2, pricePerServing: price, difficulty: minutes <= 25 ? 'Einfach' : 'Mittel', diet, tags, nutrition, ingredients, steps })

export const recipes: Recipe[] = [
  r('tomatenpasta','Cremige Tomatenpasta','Samtige Sauce, knusprige Brösel und viel Basilikum.',img('photo-1473093295043-cdd812d0e601'),22,2.7,'vegetarisch',['italienisch','comfort'],{kcal:610,protein:21,carbs:88,fat:19,fiber:9},[i('pasta','Pasta',220,'g','Trockenwaren',0.7),i('tomate','Tomaten',400,'g','Gemüse',1.6),i('frischkaese','Frischkäse',100,'g','Kühlregal',0.9),i('basilikum','Basilikum',15,'g','Gemüse',0.7)],['Pasta bissfest kochen.','Tomaten kräftig einkochen.','Frischkäse einrühren und mit Pasta verbinden.']),
  r('kichererbsencurry','Kichererbsen-Curry','Wärmend, kokosig und in einer Pfanne fertig.',img('photo-1603894584373-5ac82b2ae398'),28,2.4,'vegan',['indisch','meal-prep'],{kcal:540,protein:19,carbs:68,fat:22,fiber:15},[i('kichererbse','Kichererbsen',400,'g','Trockenwaren',1.1),i('tomate','Tomaten',300,'g','Gemüse',1.2),i('kokosmilch','Kokosmilch',200,'ml','Trockenwaren',1.0),i('spinat','Spinat',150,'g','Gemüse',1.2)],['Gewürze anrösten.','Tomaten und Kichererbsen köcheln.','Kokosmilch und Spinat unterheben.']),
  r('ofengemuese','Ofengemüse mit Feta','Röstgemüse, salziger Feta und Zitronen-Joghurt.',img('photo-1547592180-85f173990554'),35,3.1,'vegetarisch',['mediterran','proteinreich'],{kcal:480,protein:23,carbs:42,fat:24,fiber:11},[i('paprika','Paprika',250,'g','Gemüse',1.6),i('zucchini','Zucchini',250,'g','Gemüse',1.3),i('kartoffel','Kartoffeln',400,'g','Gemüse',0.8),i('feta','Feta',150,'g','Kühlregal',1.7)],['Gemüse schneiden und würzen.','Bei 210 °C rösten.','Feta darüberbröseln.']),
  r('linsenbolognese','Linsen-Bolognese','Herzhaft, günstig und am nächsten Tag noch besser.',img('photo-1621996346565-e3dbc646d9a9'),32,2.2,'vegan',['italienisch','meal-prep'],{kcal:590,protein:27,carbs:92,fat:10,fiber:20},[i('pasta','Pasta',220,'g','Trockenwaren',0.7),i('linse','Rote Linsen',180,'g','Trockenwaren',0.8),i('tomate','Tomaten',500,'g','Gemüse',2.0),i('karotte','Karotten',160,'g','Gemüse',0.4)],['Gemüse fein würfeln und anbraten.','Linsen und Tomaten 20 Minuten köcheln.','Mit Pasta servieren.']),
  r('tacos','Smoky Bean Tacos','Knackig, frisch und perfekt zum Teilen.',img('photo-1551504734-5ee1c4a1479b'),24,3.3,'vegan',['mexikanisch','schnell'],{kcal:560,protein:22,carbs:75,fat:18,fiber:17},[i('tortilla','Tortillas',6,'Stk','Backwaren',1.5),i('bohne','Kidneybohnen',400,'g','Trockenwaren',1.1),i('paprika','Paprika',200,'g','Gemüse',1.3),i('avocado','Avocado',1,'Stk','Gemüse',1.4)],['Bohnen rauchig anbraten.','Gemüse schneiden.','Tortillas füllen und rollen.']),
  r('reisbowl','Sesam-Reis-Bowl','Buntes Gemüse, knuspriger Tofu und Sesam-Dressing.',img('photo-1547592180-85f173990554'),30,3.5,'vegan',['asiatisch','bowl'],{kcal:630,protein:28,carbs:82,fat:21,fiber:10},[i('reis','Reis',180,'g','Trockenwaren',0.6),i('tofu','Tofu',250,'g','Kühlregal',2.0),i('karotte','Karotten',150,'g','Gemüse',0.4),i('gurke','Gurke',200,'g','Gemüse',0.8)],['Reis kochen.','Tofu knusprig braten.','Gemüse schneiden und alles anrichten.']),
  r('shakshuka','Grüne Shakshuka','Eier in würzigem Spinat mit frischem Brot.',img('photo-1590412200988-a436970781fa'),25,3.0,'vegetarisch',['orientalisch','proteinreich'],{kcal:500,protein:29,carbs:41,fat:23,fiber:8},[i('ei','Eier',4,'Stk','Kühlregal',1.5),i('spinat','Spinat',300,'g','Gemüse',2.1),i('frischkaese','Frischkäse',80,'g','Kühlregal',0.8),i('brot','Brot',250,'g','Backwaren',1.2)],['Spinat würzig einkochen.','Mulden formen und Eier hineingeben.','Abgedeckt stocken lassen.']),
  r('gnocchi','Gnocchi-Pfanne Primavera','Goldbraune Gnocchi mit Gemüse und Zitrone.',img('photo-1551183053-bf91a1d81141'),20,3.2,'vegetarisch',['italienisch','schnell'],{kcal:650,protein:20,carbs:94,fat:22,fiber:8},[i('gnocchi','Gnocchi',500,'g','Kühlregal',2.2),i('zucchini','Zucchini',220,'g','Gemüse',1.1),i('tomate','Tomaten',250,'g','Gemüse',1.0),i('feta','Feta',100,'g','Kühlregal',1.2)],['Gnocchi goldbraun braten.','Gemüse kurz mitbraten.','Mit Zitrone und Feta vollenden.']),
  r('haehnchenblech','Paprika-Hähnchen vom Blech','Saftiges Hähnchen und Kartoffeln ohne Abwaschchaos.',img('photo-1532550907401-a500c9a57435'),40,4.7,'omnivor',['deutsch','meal-prep'],{kcal:690,protein:54,carbs:58,fat:26,fiber:8},[i('haehnchen','Hähnchen',400,'g','Fleisch',4.8),i('kartoffel','Kartoffeln',500,'g','Gemüse',1.0),i('paprika','Paprika',250,'g','Gemüse',1.6),i('joghurt','Joghurt',150,'g','Kühlregal',0.6)],['Alles würzen und aufs Blech geben.','35 Minuten rösten.','Mit Joghurt servieren.']),
  r('kartoffelsuppe','Kartoffel-Lauch-Suppe','Cremig, unkompliziert und ideal zum Vorkochen.',img('photo-1547592166-23ac45744acd'),35,1.9,'vegan',['deutsch','meal-prep'],{kcal:430,protein:12,carbs:70,fat:12,fiber:11},[i('kartoffel','Kartoffeln',600,'g','Gemüse',1.2),i('lauch','Lauch',250,'g','Gemüse',1.1),i('hafercuisine','Hafercuisine',150,'ml','Trockenwaren',0.9),i('brot','Brot',200,'g','Backwaren',1.0)],['Gemüse anschwitzen.','Mit Brühe weich kochen.','Teilweise pürieren und abschmecken.']),
  r('couscous','Couscous mit Ofenkarotten','Zitronig, kräutrig und schnell vorbereitet.',img('photo-1540420773420-3366772f4999'),27,2.6,'vegan',['mediterran','bowl'],{kcal:520,protein:17,carbs:81,fat:14,fiber:12},[i('couscous','Couscous',180,'g','Trockenwaren',0.7),i('karotte','Karotten',350,'g','Gemüse',0.9),i('kichererbse','Kichererbsen',240,'g','Trockenwaren',0.8),i('spinat','Spinat',100,'g','Gemüse',0.8)],['Karotten rösten.','Couscous quellen lassen.','Mit Kichererbsen und Grün vermengen.']),
  r('salat','Crunchy Nudel-Salat','Frisch, sättigend und ideal für unterwegs.',img('photo-1512621776951-a57141f2eefd'),18,2.8,'vegan',['asiatisch','schnell'],{kcal:510,protein:16,carbs:72,fat:18,fiber:9},[i('nudeln','Reisnudeln',180,'g','Trockenwaren',1.2),i('gurke','Gurke',220,'g','Gemüse',0.9),i('karotte','Karotten',160,'g','Gemüse',0.4),i('erdnuss','Erdnüsse',60,'g','Trockenwaren',0.8)],['Nudeln garen und abschrecken.','Gemüse fein schneiden.','Mit Limetten-Dressing vermengen.']),
]
