import type { Allergen, Category, Diet, Ingredient, Recipe } from './domain/types'
import { editorialAppRecipes } from './data/editorialRecipes'

const img = (id: string) => `/recipes/${id}.jpg`
const ingredientAllergens: Partial<Record<string, Allergen[]>> = {
  pasta: ['gluten'], nudeln: ['gluten'], brot: ['gluten'], tortilla: ['gluten'], couscous: ['gluten'], gnocchi: ['gluten'],
  frischkaese: ['milch'], feta: ['milch'], joghurt: ['milch'], ei: ['ei'], tofu: ['soja'], erdnuss: ['erdnuss'],
}
const i = (id: string, name: string, amount: number, unit: string, category: Category, estimatedCost: number): Ingredient => ({ id, name, amount, unit, category, estimatedCost, allergens: ingredientAllergens[id] })
const r = (id: string, title: string, description: string, image: string, minutes: number, price: number, diet: Diet, tags: string[], nutrition: Recipe['nutrition'], ingredients: Ingredient[], steps: string[]): Recipe => ({ id, title, description, image, imageStatus: 'individual-visual-pass', minutes, activeMinutes: Math.max(10, minutes - 8), servings: 2, pricePerServing: price, difficulty: minutes <= 25 ? 'Einfach' : 'Mittel', diet, tags, nutrition, ingredients, steps })

export const recipes: Recipe[] = [
  r('tomatenpasta','Cremige Tomatenpasta','Samtige Sauce, knusprige Brösel und viel Basilikum.',img('tomatenpasta'),22,2.7,'vegetarisch',['italienisch','comfort'],{kcal:610,protein:21,carbs:88,fat:19,fiber:9},[i('pasta','Pasta',220,'g','Trockenwaren',0.7),i('tomate','Tomaten',400,'g','Gemüse',1.6),i('frischkaese','Frischkäse',100,'g','Kühlregal',0.9),i('basilikum','Basilikum',15,'g','Gemüse',0.7)],['Salzwasser aufkochen und die Pasta nach Packungsangabe bissfest garen.','Tomaten grob zerkleinern und in einer großen Pfanne acht Minuten kräftig einkochen.','Frischkäse mit zwei Esslöffeln Pastawasser glatt in die Tomatensauce rühren.','Pasta abgießen, mit der Sauce vermengen und zwei Minuten ziehen lassen.','Basilikum abzupfen, über die Pasta geben und sofort servieren.']),
  r('kichererbsencurry','Kichererbsen-Curry','Wärmend, kokosig und in einer Pfanne fertig.',img('kichererbsencurry'),28,2.4,'vegan',['indisch','meal-prep'],{kcal:540,protein:19,carbs:68,fat:22,fiber:15},[i('kichererbse','Kichererbsen',400,'g','Trockenwaren',1.1),i('tomate','Tomaten',300,'g','Gemüse',1.2),i('kokosmilch','Kokosmilch',200,'ml','Trockenwaren',1.0),i('spinat','Spinat',150,'g','Gemüse',1.2)],['Kichererbsen abspülen, Tomaten würfeln und Spinat gründlich waschen.','Currypulver in einer tiefen Pfanne eine Minute trocken anrösten.','Tomaten und Kichererbsen zugeben und acht Minuten offen köcheln lassen.','Kokosmilch einrühren und das Curry weitere acht Minuten sanft köcheln.','Spinat portionsweise unterheben, zusammenfallen lassen und kräftig abschmecken.']),
  r('ofengemuese','Ofengemüse mit Feta','Röstgemüse, salziger Feta und Zitronen-Joghurt.',img('ofengemuese'),35,3.1,'vegetarisch',['mediterran','proteinreich'],{kcal:480,protein:23,carbs:42,fat:24,fiber:11},[i('paprika','Paprika',250,'g','Gemüse',1.6),i('zucchini','Zucchini',250,'g','Gemüse',1.3),i('kartoffel','Kartoffeln',400,'g','Gemüse',0.8),i('feta','Feta',150,'g','Kühlregal',1.7)],['Backofen auf 210 °C Ober-/Unterhitze vorheizen und ein Blech bereitstellen.','Kartoffeln in schmale Spalten schneiden und zehn Minuten vorgaren.','Paprika und Zucchini schneiden, mit den Kartoffeln würzen und auf dem Blech verteilen.','Gemüse 20 Minuten rösten, wenden und weitere fünf Minuten bräunen.','Feta darüberbröseln und das Blech vor dem Servieren zwei Minuten ruhen lassen.']),
  r('linsenbolognese','Linsen-Bolognese','Herzhaft, günstig und am nächsten Tag noch besser.',img('linsenbolognese'),32,2.2,'vegan',['italienisch','meal-prep'],{kcal:590,protein:27,carbs:92,fat:10,fiber:20},[i('pasta','Pasta',220,'g','Trockenwaren',0.7),i('linse','Rote Linsen',180,'g','Trockenwaren',0.8),i('tomate','Tomaten',500,'g','Gemüse',2.0),i('karotte','Karotten',160,'g','Gemüse',0.4)],['Karotten fein würfeln und in einem Topf fünf Minuten anschwitzen.','Linsen abspülen, mit den Tomaten zugeben und mit Wasser knapp bedecken.','Sauce 20 Minuten sanft köcheln lassen und bei Bedarf Wasser nachgießen.','Währenddessen Pasta in Salzwasser bissfest kochen und abgießen.','Bolognese kräftig abschmecken, mit der Pasta vermengen und heiß servieren.']),
  r('tacos','Smoky Bean Tacos','Knackig, frisch und perfekt zum Teilen.',img('tacos'),24,3.3,'vegan',['mexikanisch','schnell'],{kcal:560,protein:22,carbs:75,fat:18,fiber:17},[i('tortilla','Tortillas',6,'Stk','Backwaren',1.5),i('bohne','Kidneybohnen',400,'g','Trockenwaren',1.1),i('paprika','Paprika',200,'g','Gemüse',1.3),i('avocado','Avocado',1,'Stk','Gemüse',1.4)],['Bohnen abspülen, Paprika würfeln und Avocado in Scheiben schneiden.','Paprika in einer Pfanne fünf Minuten kräftig braten.','Bohnen zugeben, rauchig würzen und weitere fünf Minuten erhitzen.','Tortillas nacheinander in einer trockenen Pfanne je 30 Sekunden erwärmen.','Tortillas mit Bohnen, Paprika und Avocado füllen, zusammenklappen und servieren.']),
  r('reisbowl','Sesam-Reis-Bowl','Buntes Gemüse, knuspriger Tofu und Sesam-Dressing.',img('reisbowl'),30,3.5,'vegan',['asiatisch','bowl'],{kcal:630,protein:28,carbs:82,fat:21,fiber:10},[i('reis','Reis',180,'g','Trockenwaren',0.6),i('tofu','Tofu',250,'g','Kühlregal',2.0),i('karotte','Karotten',150,'g','Gemüse',0.4),i('gurke','Gurke',200,'g','Gemüse',0.8)],['Reis gründlich waschen und nach Packungsangabe zugedeckt garen.','Tofu trocken tupfen, würfeln und in einer heißen Pfanne rundum knusprig braten.','Karotten in feine Stifte und Gurke in dünne Halbmonde schneiden.','Tofu mit Sesam, Sojasauce und einem Schuss Wasser glasieren.','Reis auf Schalen verteilen und Gemüse sowie Tofu getrennt darauf anrichten.']),
  r('shakshuka','Grüne Shakshuka','Eier in würzigem Spinat mit frischem Brot.',img('shakshuka'),25,3.0,'vegetarisch',['orientalisch','proteinreich'],{kcal:500,protein:29,carbs:41,fat:23,fiber:8},[i('ei','Eier',4,'Stk','Kühlregal',1.5),i('spinat','Spinat',300,'g','Gemüse',2.1),i('frischkaese','Frischkäse',80,'g','Kühlregal',0.8),i('brot','Brot',250,'g','Backwaren',1.2)],['Spinat waschen und in einer großen Pfanne portionsweise zusammenfallen lassen.','Spinat würzen und fünf Minuten offen einkochen, bis kaum Flüssigkeit bleibt.','Frischkäse einrühren und vier gleichmäßige Mulden formen.','Eier einzeln in die Mulden schlagen und zugedeckt sechs bis acht Minuten stocken lassen.','Brot in Scheiben schneiden und zur noch heißen Shakshuka reichen.']),
  r('gnocchi','Gnocchi-Pfanne Primavera','Goldbraune Gnocchi mit Gemüse und Zitrone.',img('gnocchi'),20,3.2,'vegetarisch',['italienisch','schnell'],{kcal:650,protein:20,carbs:94,fat:22,fiber:8},[i('gnocchi','Gnocchi',500,'g','Kühlregal',2.2),i('zucchini','Zucchini',220,'g','Gemüse',1.1),i('tomate','Tomaten',250,'g','Gemüse',1.0),i('feta','Feta',100,'g','Kühlregal',1.2)],['Zucchini längs halbieren und zusammen mit den Tomaten mundgerecht schneiden.','Gnocchi in einer großen Pfanne acht Minuten rundum goldbraun braten.','Zucchini zugeben und vier Minuten unter häufigem Wenden mitbraten.','Tomaten untermischen und zwei Minuten erhitzen, ohne sie zerfallen zu lassen.','Feta darüberbröseln, mit Zitronensaft abschmecken und sofort servieren.']),
  r('haehnchenblech','Paprika-Hähnchen vom Blech','Saftiges Hähnchen und Kartoffeln ohne Abwaschchaos.',img('haehnchenblech'),40,4.7,'omnivor',['deutsch','meal-prep'],{kcal:690,protein:54,carbs:58,fat:26,fiber:8},[i('haehnchen','Hähnchen',400,'g','Fleisch',4.8),i('kartoffel','Kartoffeln',500,'g','Gemüse',1.0),i('paprika','Paprika',250,'g','Gemüse',1.6),i('joghurt','Joghurt',150,'g','Kühlregal',0.6)],['Backofen auf 210 °C Ober-/Unterhitze vorheizen und ein Blech einölen.','Kartoffeln in Spalten schneiden, würzen und zehn Minuten allein vorbacken.','Paprika schneiden, Hähnchen trocken tupfen und beides kräftig mit Paprika würzen.','Hähnchen und Paprika zugeben und 25 Minuten rösten, bis das Fleisch 75 °C Kerntemperatur erreicht.','Blech fünf Minuten ruhen lassen und anschließend mit Joghurt servieren.']),
  r('kartoffelsuppe','Kartoffel-Lauch-Suppe','Cremig, unkompliziert und ideal zum Vorkochen.',img('kartoffelsuppe'),35,1.9,'vegan',['deutsch','meal-prep'],{kcal:430,protein:12,carbs:70,fat:12,fiber:11},[i('kartoffel','Kartoffeln',600,'g','Gemüse',1.2),i('lauch','Lauch',250,'g','Gemüse',1.1),i('hafercuisine','Hafercuisine',150,'ml','Trockenwaren',0.9),i('brot','Brot',200,'g','Backwaren',1.0)],['Kartoffeln schälen und würfeln, Lauch gründlich waschen und in Ringe schneiden.','Ein Drittel des Lauchs beiseitelegen, den Rest mit den Kartoffeln fünf Minuten anschwitzen.','Mit 900 Millilitern Gemüsebrühe ablöschen und 20 Minuten weich kochen.','Hafercuisine einrühren und die Suppe nur teilweise pürieren, sodass Stücke bleiben.','Restlichen Lauch kurz anbraten, auf der Suppe verteilen und Brot dazu reichen.']),
  r('couscous','Couscous mit Ofenkarotten','Zitronig, kräutrig und schnell vorbereitet.',img('couscous'),27,2.6,'vegan',['mediterran','bowl'],{kcal:520,protein:17,carbs:81,fat:14,fiber:12},[i('couscous','Couscous',180,'g','Trockenwaren',0.7),i('karotte','Karotten',350,'g','Gemüse',0.9),i('kichererbse','Kichererbsen',240,'g','Trockenwaren',0.8),i('spinat','Spinat',100,'g','Gemüse',0.8)],['Backofen auf 220 °C Ober-/Unterhitze vorheizen und Karotten schräg in Stücke schneiden.','Karotten würzen und auf einem Blech 20 Minuten rösten, nach der Hälfte wenden.','Couscous mit der gleichen Menge kochendem Salzwasser übergießen und zehn Minuten zugedeckt quellen lassen.','Kichererbsen abspülen, Spinat waschen und beides unter den aufgelockerten Couscous heben.','Ofenkarotten darauf verteilen, mit Zitronensaft abschmecken und warm servieren.']),
  r('salat','Crunchy Nudel-Salat','Frisch, sättigend und ideal für unterwegs.',img('salat'),18,2.8,'vegan',['asiatisch','schnell'],{kcal:510,protein:16,carbs:72,fat:18,fiber:9},[i('nudeln','Reisnudeln',180,'g','Trockenwaren',1.2),i('gurke','Gurke',220,'g','Gemüse',0.9),i('karotte','Karotten',160,'g','Gemüse',0.4),i('erdnuss','Erdnüsse',60,'g','Trockenwaren',0.8)],['Reisnudeln nach Packungsangabe garen, kalt abschrecken und gut abtropfen lassen.','Gurke in Halbmonde und Karotten in sehr feine Stifte schneiden.','Limettensaft mit Sojasauce und einem Schuss Wasser zu einem Dressing verrühren.','Nudeln und Gemüse gründlich mit dem Dressing vermengen.','Erdnüsse grob hacken, erst kurz vor dem Servieren darüberstreuen und den Salat kühl stellen.']),
  ...editorialAppRecipes,
]
